"""
Portable Packager.

Assembles the final portable application:

  output/
  ├── AppName.exe              ← Main launcher (generated)
  ├── _portablizer/
  │   ├── launcher.bat         ← Batch launcher (Windows fallback)
  │   ├── launcher_config.json ← App metadata & paths
  │   ├── registry_redirects.json
  │   └── first_run.ps1        ← First-run setup script
  ├── registry_import.reg      ← Pre-populate HKCU registry (optional)
  ├── app/                     ← The actual application files
  │   ├── AppName.exe
  │   ├── *.dll
  │   └── ...
  └── README.txt
"""

import os
import json
import shutil
import logging
import platform
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, List

log = logging.getLogger(__name__)
IS_WINDOWS = platform.system() == "Windows"

# File extensions to flag as potentially admin-requiring
SUSPECT_EXTENSIONS = {".sys", ".drv"}
SUSPECT_NAMES = {"install.exe", "setup.exe", "uninstall.exe", "updater.exe",
                 "update.exe", "autoupdate.exe", "maintenance.exe"}


@dataclass
class PackageResult:
    success: bool = True
    file_count: int = 0
    warnings: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)


class PortablePackager:

    def __init__(self, config, installer_info):
        self.config = config
        self.info = installer_info
        self.out = config.output_path

    def package(self, app_root: Path) -> PackageResult:
        result = PackageResult()

        # 1. Copy app files into output/app/
        app_dest = self.out / "app"
        app_dest.mkdir(parents=True, exist_ok=True)
        log.info(f"Copying app files: {app_root} → {app_dest}")
        self._copy_tree(app_root, app_dest)
        result.file_count = sum(1 for _ in app_dest.rglob("*") if _.is_file())

        # 2. Detect main executable
        main_exe = self._find_main_exe(app_dest)
        if main_exe:
            log.info(f"Detected main executable: {main_exe.name}")
        else:
            result.warnings.append("Could not auto-detect the main .exe — check the app/ folder.")

        # 3. Check for suspect files (drivers, services)
        suspects = self._scan_for_suspects(app_dest)
        for s in suspects:
            if s.suffix.lower() == ".sys":
                result.limitations.append(
                    f"Kernel driver found: {s.name} — this component requires admin to load."
                )
            elif s.name.lower() in SUSPECT_NAMES:
                result.warnings.append(
                    f"Found '{s.name}' — auto-update or installer sub-component may need admin."
                )

        # 4. Create _portablizer/ metadata directory
        meta = self.out / "_portablizer"
        meta.mkdir(exist_ok=True)

        # 5. Write launcher config
        app_name = (self.info.app_name or self.config.input_path.stem).strip()
        launcher_config = self._build_launcher_config(main_exe, app_name)
        (meta / "launcher_config.json").write_text(
            json.dumps(launcher_config, indent=2), encoding="utf-8"
        )

        # 6. Write batch launcher (works without any dependencies)
        bat_path = meta / "launcher.bat"
        self._write_batch_launcher(bat_path, main_exe, launcher_config)

        # 7. Write PowerShell launcher (richer redirect support)
        ps1_path = meta / "launcher.ps1"
        self._write_ps1_launcher(ps1_path, main_exe, launcher_config)

        # 8. Write first-run setup script
        fr_path = meta / "first_run.ps1"
        self._write_first_run_script(fr_path, launcher_config)

        # 9. Write top-level launch shortcut (.bat) for easy access
        top_bat = self.out / f"Launch {app_name}.bat"
        top_bat.write_text(
            f'@echo off\r\ncall "%~dp0_portablizer\\launcher.bat" %*\r\n',
            encoding="ascii"
        )

        # 10. Write README
        readme_path = self.out / "README.txt"
        self._write_readme(readme_path, app_name, main_exe, result)

        log.info(f"Packaging complete: {result.file_count} files in {self.out}")
        return result

    # ──────────────────────────────────────────────────────────────────────────
    # Launcher generators
    # ──────────────────────────────────────────────────────────────────────────

    def _write_batch_launcher(self, path: Path, main_exe: Optional[Path], cfg: dict):
        app_name = cfg.get("app_name", "App")
        rel_exe = cfg.get("main_exe_rel", "app\\app.exe")
        appdata_subdir = cfg.get("appdata_subdir", app_name)

        bat = f"""\
@echo off
setlocal enabledelayedexpansion

:: ============================================================
:: Portable Launcher - generated by Portablizer
:: ============================================================

set "SCRIPT_DIR=%~dp0"
set "PORTABLIZER_ROOT=%SCRIPT_DIR%.."
set "APP_ROOT=%PORTABLIZER_ROOT%\\app"

:: Set up portable data directory (next to this launcher, not in AppData)
set "PORTABLE_DATA=%PORTABLIZER_ROOT%\\data"
if not exist "%PORTABLE_DATA%" mkdir "%PORTABLE_DATA%"

:: Redirect AppData to local portable folder
set "APPDATA=%PORTABLE_DATA%\\AppData\\Roaming"
set "LOCALAPPDATA=%PORTABLE_DATA%\\AppData\\Local"
set "USERPROFILE=%PORTABLE_DATA%"
set "HOMEDRIVE=%PORTABLE_DATA:~0,2%"
set "HOMEPATH=%PORTABLE_DATA:~2%"

:: Ensure AppData dirs exist
if not exist "%APPDATA%" mkdir "%APPDATA%"
if not exist "%LOCALAPPDATA%" mkdir "%LOCALAPPDATA%"

:: First run: import registry if needed
set "FIRST_RUN_FLAG=%PORTABLE_DATA%\\.portablizer_initialized"
if not exist "%FIRST_RUN_FLAG%" (
    call :first_run
    echo. > "%FIRST_RUN_FLAG%"
)

:: Launch the application
set "MAIN_EXE=%APP_ROOT%\\{rel_exe.replace("app\\", "")}"
if not exist "%MAIN_EXE%" (
    echo ERROR: Application executable not found: %MAIN_EXE%
    echo Please check the app\\ directory.
    pause
    exit /b 1
)

start "" "%MAIN_EXE%" %*
exit /b 0

:first_run
echo [Portablizer] First run setup...
:: Import registry redirects if available
set "REG_FILE=%PORTABLIZER_ROOT%\\registry_import.reg"
if exist "%REG_FILE%" (
    echo [Portablizer] Importing registry settings...
    reg import "%REG_FILE%" >nul 2>&1
)
:: Run first-run PowerShell script if available
set "PS1=%~dp0first_run.ps1"
if exist "%PS1%" (
    powershell -ExecutionPolicy Bypass -File "%PS1%" -PortableRoot "%PORTABLIZER_ROOT%"
)
exit /b 0
"""
        path.write_text(bat, encoding="utf-8")

    def _write_ps1_launcher(self, path: Path, main_exe: Optional[Path], cfg: dict):
        app_name = cfg.get("app_name", "App")
        rel_exe = cfg.get("main_exe_rel", "app\\app.exe")

        ps1 = f"""\
# ============================================================
# Portable Launcher (PowerShell) — generated by Portablizer
# App: {app_name}
# ============================================================

param([string]$PortableRoot = "")

if (-not $PortableRoot) {{
    $PortableRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
}}

$AppRoot     = Join-Path $PortableRoot "app"
$DataDir     = Join-Path $PortableRoot "data"
$AppDataDir  = Join-Path $DataDir "AppData\\Roaming"
$LocalAppDir = Join-Path $DataDir "AppData\\Local"
$TempDir     = Join-Path $DataDir "Temp"
$MainExe     = Join-Path $AppRoot "{rel_exe.replace("app\\", "")}"

# Create portable data directories
@($DataDir, $AppDataDir, $LocalAppDir, $TempDir) | ForEach-Object {{
    if (-not (Test-Path $_)) {{ New-Item -ItemType Directory -Path $_ | Out-Null }}
}}

# Redirect environment to portable paths
$env:APPDATA      = $AppDataDir
$env:LOCALAPPDATA = $LocalAppDir
$env:USERPROFILE  = $DataDir
$env:TEMP         = $TempDir
$env:TMP          = $TempDir

# First-run initialization
$initFlag = Join-Path $DataDir ".portablizer_initialized"
if (-not (Test-Path $initFlag)) {{
    Write-Host "[Portablizer] First run setup..."
    $regFile = Join-Path $PortableRoot "registry_import.reg"
    if (Test-Path $regFile) {{
        Write-Host "[Portablizer] Importing registry settings..."
        reg import $regFile 2>&1 | Out-Null
    }}
    New-Item -ItemType File -Path $initFlag | Out-Null
}}

# Launch
if (-not (Test-Path $MainExe)) {{
    Write-Error "Main executable not found: $MainExe"
    exit 1
}}

Write-Host "[Portablizer] Launching: $MainExe"
& $MainExe @args
"""
        path.write_text(ps1, encoding="utf-8")

    def _write_first_run_script(self, path: Path, cfg: dict):
        app_name = cfg.get("app_name", "App")
        ps1 = f"""\
# First-run setup script for portable {app_name}
# Runs once when the portable app is first launched.

param([string]$PortableRoot = "")

Write-Host "[Portablizer] Running first-time setup for {app_name}..."

# Register app-local COM servers if needed
$comManifest = Join-Path $PortableRoot "app\\app.manifest"
if (Test-Path $comManifest) {{
    Write-Host "[Portablizer] Registering COM components (user-scope)..."
    # Registration-free COM is preferred; this handles legacy cases
}}

# Create Start Menu shortcut in user profile (no admin needed)
$startMenu = Join-Path $env:APPDATA "Microsoft\\Windows\\Start Menu\\Programs"
$shortcutPath = Join-Path $startMenu "{app_name} (Portable).lnk"

if (!(Test-Path $shortcutPath)) {{
    try {{
        $WScriptShell = New-Object -ComObject WScript.Shell
        $shortcut = $WScriptShell.CreateShortcut($shortcutPath)
        $shortcut.TargetPath = Join-Path $PortableRoot "_portablizer\\launcher.bat"
        $shortcut.WorkingDirectory = $PortableRoot
        $shortcut.Description = "{app_name} (Portable - no admin required)"
        $shortcut.Save()
        Write-Host "[Portablizer] Created Start Menu shortcut."
    }} catch {{
        Write-Host "[Portablizer] Could not create Start Menu shortcut: $_"
    }}
}}

Write-Host "[Portablizer] First-run setup complete."
"""
        path.write_text(ps1, encoding="utf-8")

    def _write_readme(self, path: Path, app_name: str, main_exe: Optional[Path],
                      result: PackageResult):
        warnings_text = ""
        if result.warnings:
            warnings_text = "\nWARNINGS:\n" + "\n".join(f"  • {w}" for w in result.warnings) + "\n"

        limitations_text = ""
        if result.limitations:
            limitations_text = "\nKNOWN LIMITATIONS:\n" + "\n".join(
                f"  ⚠ {l}" for l in result.limitations) + "\n"

        exe_name = main_exe.name if main_exe else "the main .exe in the app/ folder"
        readme = f"""\
╔══════════════════════════════════════════════════════════════╗
║          {app_name:^52} ║
║              (Portable Edition — No Admin Required)          ║
╚══════════════════════════════════════════════════════════════╝

This portable package was created by Portablizer.
It runs without administrator privileges and stores all data
locally within this folder (nothing written to system directories).

── HOW TO RUN ─────────────────────────────────────────────────

  Double-click:  "Launch {app_name}.bat"
  
  Or directly:   app\\{exe_name}
  
  PowerShell:    _portablizer\\launcher.ps1

── FOLDER STRUCTURE ───────────────────────────────────────────

  app\\                  Application files
  data\\                 User data & settings (created on first run)
  _portablizer\\         Launcher scripts and config
  registry_import.reg   Registry settings (imported on first run)
  Launch {app_name}.bat  ← START HERE

── PORTABILITY ────────────────────────────────────────────────

  All user data is stored in data\\ within this folder.
  You can move or copy this entire folder to any location
  or USB drive without reconfiguring anything.
{warnings_text}{limitations_text}
── CREATED BY ─────────────────────────────────────────────────

  Portablizer — https://github.com/portablizer/portablizer
  Conversion date: {__import__('datetime').date.today()}
"""
        path.write_text(readme, encoding="utf-8")

    # ──────────────────────────────────────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _build_launcher_config(self, main_exe: Optional[Path], app_name: str) -> dict:
        rel_exe = ""
        if main_exe:
            try:
                rel_exe = str(main_exe.relative_to(self.out / "app"))
            except ValueError:
                rel_exe = main_exe.name

        return {
            "app_name": app_name,
            "publisher": self.info.publisher or "",
            "installer_type": self.info.installer_type,
            "main_exe_rel": rel_exe,
            "appdata_subdir": app_name,
            "created_by": "portablizer",
        }

    def _find_main_exe(self, app_dir: Path) -> Optional[Path]:
        """
        Heuristic: find the most likely main executable.
        Prefers top-level .exe with name similar to the app name.
        """
        app_name_lower = (self.info.app_name or self.config.input_path.stem).lower()
        exes = list(app_dir.rglob("*.exe"))
        if not exes:
            return None

        # Filter out known non-main executables
        skip = {"uninstall", "uninst", "setup", "install", "update", "updater",
                 "crash", "reporter", "helper", "browser_crashpad_handler",
                 "maintenance", "elevate"}

        candidates = [e for e in exes
                      if not any(s in e.stem.lower() for s in skip)]
        if not candidates:
            candidates = exes

        # Prefer .exe in top-level app dir
        top_level = [e for e in candidates if e.parent == app_dir]
        if top_level:
            candidates = top_level

        # Score by name similarity
        def score(exe: Path) -> float:
            name = exe.stem.lower()
            # Exact match
            if name == app_name_lower:
                return 100.0
            # Contains app name
            if app_name_lower in name or name in app_name_lower:
                return 50.0
            # Prefer shorter names (main exe tends to be simple)
            return max(0, 20 - len(name))

        candidates.sort(key=score, reverse=True)
        return candidates[0] if candidates else exes[0]

    def _scan_for_suspects(self, app_dir: Path) -> List[Path]:
        suspects = []
        for f in app_dir.rglob("*"):
            if f.is_file():
                if f.suffix.lower() in SUSPECT_EXTENSIONS:
                    suspects.append(f)
                elif f.name.lower() in SUSPECT_NAMES:
                    suspects.append(f)
        return suspects

    def _copy_tree(self, src: Path, dst: Path):
        for item in src.iterdir():
            s = src / item.name
            d = dst / item.name
            if s.is_dir():
                d.mkdir(parents=True, exist_ok=True)
                self._copy_tree(s, d)
            else:
                try:
                    shutil.copy2(s, d)
                except Exception as e:
                    log.warning(f"Could not copy {s.name}: {e}")
