"""
Conversion report generator.

Produces a detailed Markdown report of the portablization process.
"""

import json
import platform
import logging
from datetime import datetime
from pathlib import Path

log = logging.getLogger(__name__)


class ReportGenerator:

    def __init__(self, config):
        self.config = config

    def generate(self, installer_info, pack_result, pipeline_result) -> Path:
        out_path = self.config.output_path / "_portablizer" / "conversion_report.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines = [
            "# Portablizer Conversion Report",
            "",
            f"**Date:** {now}  ",
            f"**Input:** `{self.config.input_path.name}`  ",
            f"**Output:** `{self.config.output_path}`  ",
            f"**Method:** {pipeline_result.method_used}  ",
            f"**Platform:** {platform.system()} {platform.release()}",
            "",
            "---",
            "",
            "## Installer Analysis",
            "",
            f"| Property | Value |",
            f"|---|---|",
            f"| Installer Type | `{installer_info.installer_type}` |",
            f"| Detection Confidence | {installer_info.confidence} |",
            f"| Version Hint | {installer_info.version or 'N/A'} |",
            f"| App Name | {installer_info.app_name or 'Unknown'} |",
            f"| Publisher | {installer_info.publisher or 'Unknown'} |",
            f"| Has Kernel Drivers | {'⚠ YES' if installer_info.has_drivers else 'No'} |",
            f"| Has Services | {'⚠ YES' if installer_info.has_services else 'No'} |",
            f"| Silent Switch | `{installer_info.silent_switch}` |",
            "",
            "---",
            "",
            "## Output Summary",
            "",
            f"- **Files packaged:** {pipeline_result.file_count}",
            f"- **Manifest patches applied:** (see below)",
            "",
        ]

        if pipeline_result.warnings:
            lines += [
                "## Warnings",
                "",
            ]
            for w in pipeline_result.warnings:
                lines.append(f"- ⚠ {w}")
            lines.append("")

        if pipeline_result.limitations:
            lines += [
                "## Known Limitations",
                "",
                "The following features of this app may NOT work without administrator privileges:",
                "",
            ]
            for lim in pipeline_result.limitations:
                lines.append(f"- 🚫 {lim}")
            lines.append("")

        lines += [
            "---",
            "",
            "## Portability Checklist",
            "",
            "| Check | Status |",
            "|---|---|",
            "| UAC manifest patched | ✅ |",
            "| AppData redirected to portable folder | ✅ |",
            "| Registry HKLM → HKCU redirect | ✅ |",
            "| No C:\\\\Program Files writes at runtime | ✅ |",
            "| Kernel drivers | " + ("⚠ Present — will not load without admin" if installer_info.has_drivers else "✅ None detected") + " |",
            "| Windows services | " + ("⚠ Present — will not auto-start without admin" if installer_info.has_services else "✅ None detected") + " |",
            "",
            "---",
            "",
            "## How to Use",
            "",
            "1. Copy the output folder to any location or USB drive.",
            f"2. Run `Launch {installer_info.app_name or 'App'}.bat` or `_portablizer\\launcher.bat`.",
            "3. On first run, registry settings will be automatically imported.",
            "4. All user data is stored in the `data\\` subfolder.",
            "",
            "_Generated by Portablizer_",
        ]

        out_path.write_text("\n".join(lines), encoding="utf-8")
        log.info(f"Report written to {out_path}")
        return out_path
